### ISSUE TITLE
Bridge view and Hue Bridge view throwing a warning on click

### ISSUE THREAD

**Issue by Fisico** [diyhue/diyHueUI#2]
Bridge view and Hue Bridge view are throwing a warning on click or refresh.

```
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at label
    at div
    at form
    at div
    at div
    at VisualElementHandler (http://localhost:3000/static/js/bundle.js:210608:38)
    at MotionComponent (http://localhost:3000/static/js/bundle.js:210508:20)
    at Bridge (http://localhost:3000/static/js/src_views_Bridge_js.chunk.js:148:5)
    at Route (http://localhost:3000/static/js/bundle.js:195138:29)
    at Switch (http://localhost:3000/static/js/bundle.js:195340:29)
    at PresenceChild (http://localhost:3000/static/js/bundle.js:207363:21)
    at AnimatePresence (http://localhost:3000/static/js/bundle.js:207527:21)
    at Router (http://localhost:3000/static/js/bundle.js:194773:30)
    at HashRouter (http://localhost:3000/static/js/bundle.js:194439:35)
    at Suspense
    at div
    at TheContent (http://localhost:3000/static/js/bundle.js:397:5)
    at div
    at TheLayout (http://localhost:3000/static/js/bundle.js:720:5)
    at Suspense
    at App (http://localhost:3000/static/js/bundle.js:191:80)
```

**Comment by Fisico** [comment]
fixed with the restructure project
